name: Tests

on:
  workflow_dispatch:
  
jobs:
  Sandbox:
    runs-on: ubuntu-latest
    env:
      super_secret: ${{ secrets.ENV }}
    environment: Sandbox
    steps:
      - if: ${{ env.super_secret == 'Sandbox' }}
        run: echo 'This step will only run if the secret has Sandbox as Value.'
  Live:
    runs-on: ubuntu-latest
    env:
      super_secret: ${{ secrets.ENV }}
    environment: Live
    steps:
      - if: ${{ env.super_secret == 'Live' }}
        run: echo 'This step will only run if the secret has Live as value.'
